ALTER TABLE ligas ADD COLUMN escudo VARCHAR(255) DEFAULT NULL;
ALTER TABLE ligas ADD COLUMN escudo_bloqueado TINYINT(1) DEFAULT 0;

ALTER TABLE equipos ADD COLUMN escudo VARCHAR(255) DEFAULT NULL;
ALTER TABLE equipos ADD COLUMN escudo_bloqueado TINYINT(1) DEFAULT 0;
