ALTER TABLE usuario ADD COLUMN id_equipo INT DEFAULT NULL;
ALTER TABLE usuario ADD CONSTRAINT fk_user_equipo FOREIGN KEY (id_equipo) REFERENCES equipos(id_equipo) ON DELETE SET NULL ON UPDATE CASCADE;
